/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SayHi */

#ifndef _Included_SayHi
#define _Included_SayHi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SayHi
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SayHi_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
